services:
  - type: web
    name: app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    plan: free
    region: oregon
    pythonVersion: 3.9